
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { CheckCircle, BarChart2, Users, Shield, Target, Briefcase, ShoppingCart, Repeat, Gamepad2, FileText, Mic2, DollarSign, GitBranch, Aperture } from "lucide-react";
import type { Metadata } from 'next';
import Link from "next/link";
import { AIImage } from "@/components/ai/AIImage";

export const metadata: Metadata = {
  title: 'VSD Token Information',
  description: 'Detailed information about the VSD stablecoin, its features, tokenomics, and use cases.',
};

const FeatureItem = ({ icon: Icon, title, children }: { icon: React.ElementType, title: string, children: React.ReactNode }) => (
  <div className="flex items-start space-x-4">
    <Icon className="h-8 w-8 text-primary mt-1 shrink-0" />
    <div>
      <h3 className="text-xl font-semibold mb-1 font-headline">{title}</h3>
      <p className="text-muted-foreground">{children}</p>
    </div>
  </div>
);

const UseCaseCard = ({ icon: Icon, title, children }: { icon: React.ElementType, title: string, children: React.ReactNode }) => (
    <Card className="shadow-md h-full">
        <CardHeader className="flex flex-row items-center space-x-3 pb-2">
            <Icon className="h-6 w-6 text-primary" />
            <CardTitle className="font-headline text-xl">{title}</CardTitle>
        </CardHeader>
        <CardContent>
            <p className="text-muted-foreground text-sm">{children}</p>
        </CardContent>
    </Card>
);

export default function TokenPage() {
  return (
    <div className="space-y-12 py-8">
      <header className="text-center">
        <DollarSign className="h-12 w-12 sm:h-16 sm:w-16 text-primary mx-auto mb-4" /> {/* Adjusted icon size */}
        <h1 className="font-headline text-3xl sm:text-4xl md:text-5xl font-bold mb-4 text-primary">VSD Token Details</h1> {/* Adjusted font size */}
        <p className="text-base sm:text-lg lg:text-xl text-muted-foreground max-w-2xl mx-auto"> {/* Adjusted font size */}
          Discover the core aspects of VSD, the decentralized stablecoin designed for reliability and utility in the digital economy.
        </p>
      </header>

      <Separator />

      <section className="space-y-8">
        <h2 className="font-headline text-2xl sm:text-3xl font-semibold text-center">What is VSD?</h2>
        <Card className="shadow-lg">
          <CardContent className="p-6 sm:p-8 text-base sm:text-lg"> {/* Adjusted padding and font size */}
            <p className="mb-4">
              VSD is a decentralized, asset-backed stablecoin designed to maintain a value peg, typically to a major fiat currency like the US Dollar. It serves as a reliable medium of exchange, store of value, and unit of account within the VSD Network and the broader DeFi (Decentralized Finance) ecosystem.
            </p>
            <p>
              Built on transparent and auditable smart contracts, VSD aims to provide a resilient alternative to traditional financial systems, empowering users with greater control, efficiency, and access to innovative financial services.
            </p>
          </CardContent>
        </Card>
      </section>
      
      <Separator />

      <section className="space-y-8">
        <h2 className="font-headline text-2xl sm:text-3xl font-semibold text-center">Key Features</h2>
        <div className="grid md:grid-cols-2 gap-6 sm:gap-8"> {/* Adjusted gap */}
          <FeatureItem icon={Target} title="Decentralized & Resilient">
            VSD operates on a public blockchain, ensuring high availability and resistance to single points of failure or censorship. Smart contracts govern its core logic.
          </FeatureItem>
          <FeatureItem icon={Shield} title="Value Stability (Pegged)">
            Maintains its value peg through a combination of over-collateralization, algorithmic adjustments, and arbitrage incentives, managed by its smart contracts.
          </FeatureItem>
          <FeatureItem icon={Users} title="Community Governed (DAO)">
            Key parameters, upgrades, and risk management of the VSD platform are typically governed by VSD token holders through a Decentralized Autonomous Organization (DAO).
          </FeatureItem>
          <FeatureItem icon={BarChart2} title="Transparent & Auditable">
            All transactions, collateral backing, and smart contract logic are publicly verifiable on the blockchain, fostering trust and accountability.
          </FeatureItem>
          <FeatureItem icon={GitBranch} title="Permissionless & Composable">
            VSD can be freely held, transferred, and integrated into various DeFi protocols and dApps without requiring permission from a central authority.
          </FeatureItem>
          <FeatureItem icon={Aperture} title="Collateral-Backed">
            VSD tokens are typically generated by locking up approved digital assets as collateral in smart contract vaults, ensuring each VSD is backed by sufficient value.
          </FeatureItem>
        </div>
      </section>

      <Separator />

      <section className="space-y-8">
        <h2 className="font-headline text-2xl sm:text-3xl font-semibold text-center">Tokenomics Overview</h2>
        <Card className="shadow-lg">
          <CardHeader>
            <CardTitle className="font-headline text-xl sm:text-2xl">Understanding VSD's Economic Model</CardTitle> {/* Adjusted font size */}
             <CardDescription>VSD's tokenomics are designed for stability, utility, and ecosystem growth within the decentralized economy.</CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div>
                <h4 className="text-lg sm:text-xl font-semibold mb-2">Total Supply & Minting</h4> {/* Adjusted font size */}
                <p className="text-muted-foreground">
                The total supply of VSD is dynamic, expanding or contracting based on user demand. New VSD is minted when users deposit approved collateral assets into the platform's smart contract vaults. Conversely, VSD is burned when users repay their positions and withdraw their collateral.
                </p>
            </div>
            <div>
                <h4 className="text-lg sm:text-xl font-semibold mb-2">Collateralization</h4> {/* Adjusted font size */}
                <p className="text-muted-foreground">
                VSD is over-collateralized, meaning the value of the locked collateral exceeds the value of the minted VSD. This provides a buffer against collateral price volatility and ensures the solvency of the system. Accepted collateral types and collateralization ratios are typically managed by governance.
                </p>
            </div>
            <div>
                <h4 className="text-lg sm:text-xl font-semibold mb-2">Utility & Use Cases</h4> {/* Adjusted font size */}
                <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
                    <li><strong>Medium of Exchange:</strong> Used for payments and transfers within the VSD ecosystem and integrated dApps.</li>
                    <li><strong>Store of Value:</strong> Offers a stable alternative to volatile cryptocurrencies.</li>
                    <li><strong>DeFi Integration:</strong> Can be used as collateral in lending protocols, for liquidity provision in DEXs, yield farming, and other DeFi applications.</li>
                    <li><strong>Governance:</strong> VSD (or an associated governance token) may grant holders voting rights in the VSD DAO.</li>
                </ul>
            </div>
            <div className="bg-muted/30 p-4 sm:p-6 rounded-lg"> {/* Adjusted padding */}
              <AIImage
                initialSrc="https://placehold.co/800x400.png"
                alt="Tokenomics chart"
                width={800}
                height={400}
                className="rounded-md mx-auto shadow-md"
                hint="tokenomics crypto chart"
              />
            </div>
            <p className="text-sm text-muted-foreground text-center pt-2">
              (Example: A chart showing collateral distribution, VSD supply over time, or utility breakdown.)
            </p>
          </CardContent>
        </Card>
      </section>
      
      <Separator />
       <section className="space-y-8">
        <h2 className="font-headline text-2xl sm:text-3xl font-semibold text-center">Use Cases in Web3 & DeFi</h2>
        <p className="text-muted-foreground text-center max-w-2xl mx-auto">VSD offers a stable and efficient digital asset for a variety of decentralized applications.</p>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            <UseCaseCard icon={ShoppingCart} title="Decentralized Commerce">
                Accept VSD for payments in dApps and NFT marketplaces, offering a stable medium of exchange.
            </UseCaseCard>
            <UseCaseCard icon={Repeat} title="Lending & Borrowing">
                Use VSD as collateral to borrow other crypto assets or lend VSD to earn interest in DeFi protocols.
            </UseCaseCard>
            <UseCaseCard icon={Gamepad2} title="Play-to-Earn (P2E) Gaming">
                Integrate VSD as an in-game currency or reward mechanism in blockchain-based games.
            </UseCaseCard>
            <UseCaseCard icon={Briefcase} title="DAO Treasury Management">
                DAOs can hold VSD in their treasuries for stable value preservation and operational expenses.
            </UseCaseCard>
            <UseCaseCard icon={FileText} title="Yield Farming & Staking">
                Provide liquidity with VSD in decentralized exchanges (DEXs) or stake VSD to earn rewards.
            </UseCaseCard>
            <UseCaseCard icon={Mic2} title="Creator Economy">
                 Enable direct and stable payments in VSD for content creators, artists, and freelancers in the Web3 space.
            </UseCaseCard>
        </div>
      </section>

      <Separator />

      <section className="space-y-8">
        <h2 className="font-headline text-2xl sm:text-3xl font-semibold text-center">How to Get VSD Tokens</h2>
         <Card className="shadow-lg">
          <CardContent className="p-6 sm:p-8"> {/* Adjusted padding */}
            <p className="text-base sm:text-lg text-muted-foreground"> {/* Adjusted font size */}
              VSD tokens can typically be acquired through several avenues within the decentralized ecosystem:
            </p>
            <ul className="list-disc list-inside space-y-3 mt-4 text-base sm:text-lg text-muted-foreground pl-4"> {/* Adjusted font size */}
              <li>
                <strong>Minting:</strong> Users can generate new VSD tokens by depositing approved collateral assets into the VSD platform's smart contract vaults. (Refer to our <Link href="/developers/documentation#core-logic-modules" className="text-primary hover:underline">Core Logic documentation</Link> for details).
              </li>
              <li>
                <strong>Decentralized Exchanges (DEXs):</strong> VSD can be swapped for other cryptocurrencies on various DEXs where liquidity pools exist.
              </li>
              <li>
                <strong>Centralized Exchanges (CEXs):</strong> VSD may be listed on select centralized exchanges for trading. (Check our <Link href="/ecosystem" className="text-primary hover:underline">Ecosystem page</Link> for listed platforms).
              </li>
              <li>
                <strong>Ecosystem Participation:</strong> Some projects within the VSD ecosystem might offer VSD as rewards or incentives for activities like liquidity provision or staking.
              </li>
            </ul>
            <p className="mt-6 text-sm text-center text-primary font-medium">
              Always ensure you are interacting with official VSD smart contracts and reputable exchanges. Verify contract addresses before any transaction. DYOR (Do Your Own Research).
            </p>
          </CardContent>
        </Card>
      </section>
    </div>
  );
}
